name: TodosApp
options:
  bundleIdPrefix: com.example
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "10.0"
targets:
  TodosApp:
    type: application
    platform: iOS
    sources:
      - path: TodosApp
        excludes:
          - "Assets/*.sketch"
          - "*/.gitkeep"
    settings:
      base:
        SWIFT_VERSION: 5.0